[package]
name = "zombodb"
description = "Making Postgres and Elasticsearch work together like it's 2022"
version = "3000.1.10"
edition = "2018"
build = "build.rs"
readme = "README.md"
license = "LICENSE.md"

[lib]
crate-type = [ "cdylib" ]

[features]
default = [ "pg14" ]
pg11 = [ "pgx/pg11", "pgx-tests/pg11" ]
pg12 = [ "pgx/pg12", "pgx-tests/pg12" ]
pg13 = [ "pgx/pg13", "pgx-tests/pg13" ]
pg14 = [ "pgx/pg14", "pgx-tests/pg14" ]
pg15 = [ "pgx/pg15", "pgx-tests/pg15" ]
pg_test = [ ]

[dependencies]
byteorder = "1.4.3"
chrono = "0.4.23"
cow-utils = "0.1.2"
crossbeam = "0.8.2"
dashmap = "5.4.0"
humantime = "2.1.0"
indexmap = "1.9.2"
lalrpop-util = "0.19.8"
lazy_static = "1.4.0"
levenshtein = "1.0.5"
memoffset = "0.8.0"
num_cpus = "1.15.0"
pgx = "=0.7.3"
rayon = "1.7.0"
regex = "1.7.1"
rustc-hash = "1.1.0"
serde = { version = "1.0.154", features = [ "derive" ] }
serde_json = { version = "1.0.94", features = [ "preserve_order" ] }
serde_cbor = "0.11.2"
sqlformat = "0.2.1"
time = "0.3.20"
unicode-segmentation = "1.10.1"
ureq = { version = "2.6.2", features = [ "json" ] }
url = "2.3.1"

[build-dependencies]
lalrpop = { version = "0.19.8", features = [ "lexer" ] }
built = { version = "0.6.0", features = [ "git2", "semver" ] }

[dev-dependencies]
pgx-tests = "=0.7.3"
libc = "0.2.140"

[profile.dev]
panic = "unwind"
debug = true
opt-level = 0

[profile.dev.build-override]
opt-level = 3
debug = 0

[profile.release]
panic = "unwind"
opt-level = 3
lto = "thin"
debug = 0

[profile.artifacts]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
