[package]
name = "zombodb"
description = "Making Postgres and Elasticsearch work together like it's 2022"
version = "3000.1.3"
edition = "2018"
build = "build.rs"
readme = "README.md"
license = "LICENSE.md"

[lib]
crate-type = [ "cdylib" ]

[features]
default = [ "pg14" ]
pg10 = [ "pgx/pg10", "pgx-tests/pg10" ]
pg11 = [ "pgx/pg11", "pgx-tests/pg11" ]
pg12 = [ "pgx/pg12", "pgx-tests/pg12" ]
pg13 = [ "pgx/pg13", "pgx-tests/pg13" ]
pg14 = [ "pgx/pg14", "pgx-tests/pg14" ]
pg_test = [ ]

[dependencies]
byteorder = "1.4.3"
chrono = "0.4.22"
cow-utils = "0.1.2"
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
humantime = "2.1.0"
indexmap = "1.9.1"
lalrpop-util = "0.19.8"
lazy_static = "1.4.0"
levenshtein = "1.0.5"
memoffset = "0.6.5"
num_cpus = "1.13.1"
pgx = "0.5.2"
pgx-macros = "0.5.2"
rayon = "1.5.3"
regex = "1.6.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.145", features = [ "derive" ] }
serde_json = { version = "1.0.86", features = [ "preserve_order" ] }
serde_cbor = "0.11.2"
sqlformat = "0.2.0"
time = "0.3.15"
unicode-segmentation = "1.10.0"
ureq = { version = "2.5.0", features = [ "json" ] }
url = "2.3.1"

[build-dependencies]
lalrpop = { version = "0.19.8", features = [ "lexer" ] }
built = { version = "0.5.1", features = [ "git2", "semver" ] }

[dev-dependencies]
pgx-tests = "0.5.2"
libc = "0.2.135"

[profile.dev]
panic = "unwind"
debug = true
opt-level = 0

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
debug = 0

[profile.dev.build-override]
opt-level = 3
debug = 0
